/* CTE ON QUERY 1 */

WITH THIRD_MAX_SALARY AS(
	SELECT MAX(SALARY) AS SALARY
    FROM EMPLOYEES
    WHERE SALARY < (SELECT MAX(SALARY)
					FROM EMPLOYEES 
                    WHERE SALARY < (SELECT MAX(SALARY)
									FROM EMPLOYEES
                                    )
					)
	)

SELECT *
FROM EMPLOYEES
WHERE SALARY = (SELECT SALARY
				FROM THIRD_MAX_SALARY);
                

/* CTE ON QUERY 2 */

WITH THIRD_LOWEST_SALARY AS(
	SELECT MIN(SALARY) AS SALARY
    FROM EMPLOYEES
    WHERE SALARY > (SELECT MIN(SALARY)
					FROM EMPLOYEES 
                    WHERE SALARY > (SELECT MIN(SALARY)
									FROM EMPLOYEES
                                    )
					)
	)

SELECT *
FROM EMPLOYEES
WHERE SALARY = (SELECT SALARY
				FROM THIRD_LOWEST_SALARY);