/* THIRD LOWEST */
SELECT *
FROM EMPLOYEES
WHERE SALARY = (SELECT MIN(SALARY)
				FROM EMPLOYEES
                WHERE SALARY > (SELECT MIN(SALARY)
								FROM EMPLOYEES
								WHERE SALARY > (SELECT MIN(SALARY)
												FROM EMPLOYEES)));