SELECT *
FROM EMPLOYEES 
WHERE SALARY > 10000

-- UNION
UNION ALL
-- INTERSECT

SELECT *
FROM EMPLOYEES
WHERE DEPARTMENT_ID  = 100;

/* THE MINUS OPERATION IS NOT AVAILABLE ANYMORE IN MYSQL */
/* TO THIS, WE WOULD HAVE TO FIND ANOTHER WAY, ONE OF THEM COULD BE ... */
SELECT *
FROM EMPLOYEES
WHERE SALARY > 10000 AND DEPARTMENT_ID != 100;