USE dummydb;

/* 2nd highest salary*/
/* FINDING THE 2ND MAX SALARY*/
SELECT DISTINCT SALARY
FROM EMPLOYEES
ORDER BY SALARY DESC
LIMIT 1, 1;

SELECT *
FROM EMPLOYEES
WHERE SALARY = (SELECT DISTINCT SALARY
				FROM EMPLOYEES
				ORDER BY SALARY DESC
				LIMIT 1, 1);
        
/* FINDING THE 2ND MAX SALARY USING SUBQUERY */
SELECT MAX(SALARY)
FROM EMPLOYEES
WHERE SALARY < (SELECT MAX(SALARY)
				FROM EMPLOYEES
                );
                
SELECT *
FROM EMPLOYEES
WHERE SALARY = (SELECT MAX(SALARY)
				FROM EMPLOYEES
                WHERE SALARY < (SELECT MAX(SALARY)
								FROM EMPLOYEES
                                )
				);
                
                
/* EMPLOYEE LIST WHOSE SALARY IS GREATER THAN HIS MANAGERS SALARY */
SELECT *
FROM EMPLOYEES AS EMP
WHERE SALARY > (SELECT SALARY
				FROM EMPLOYEES AS MGR
                WHERE EMP.MANAGER_ID = MGR.EMPLOYEE_ID);
                
/* EMPLOYEE WHOSE JOB ID IS SAME AS HIS MANAGERS ID */
SELECT *
FROM EMPLOYEES AS EMP
WHERE JOB_ID = (SELECT JOB_ID
				FROM EMPLOYEES AS MGR
                WHERE EMP.MANAGER_ID = MGR.EMPLOYEE_ID);